

all: javac java
	
javac:
	javac fifteenpuzzle/Solver.java

java: 
	time java fifteenpuzzle/Solver testcases/board39.txt haha.txt 

testcases:

clean:
	rm fifteenpuzzle/*.class fifteenpuzzle/puzzle/*.class fifteenpuzzle/SolvingAlgorithms/*.class
