

all: javac java
	
javac:
	javac fifteenpuzzle/Solver.java

java: 
	java fifteenpuzzle/Solver testcases/board09.txt sol1.txt >> log.txt

testcases:


clean:
	rm fifteenpuzzle/*.class fifteenpuzzle/puzzle/*.class fifteenpuzzle/SolvingAlgorithms/*.class
